# Generated by Django 5.0.7 on 2024-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_registeruser_cart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
